"""updating nullable constraints

Revision ID: 48dc7cfbb8fb
Revises: 9cd86a3382c5
Create Date: 2019-03-21 16:12:48.450866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48dc7cfbb8fb'
down_revision = '9cd86a3382c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=False)
    op.alter_column('task', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('task', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=False)
    op.alter_column('task', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=True)
    op.alter_column('task', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('task', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=True)
    op.alter_column('task', 'status_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('task', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('status', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               nullable=True)
    # ### end Alembic commands ###
